apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  tgbot-token: {{ .Values.secrets.tgbotToken | b64enc }}
